name: Package Python Apps and create SBOM

on:
  push:
    branches: [ "master", "v1*", "v2*", "v3*", "ci" ]
    paths:
      - ".github/**"
      - 'MathTools/**'
      - 'PositionLogger/**'
      - 'control_python/**'
      - 'minimal_python/**'
      - 'monitor_python/**'
  pull_request:
    branches: [ "master", "v1*", "v2*", "v3*" ]
    paths:
      - ".github/**"
      - 'MathTools/**'
      - 'PositionLogger/**'
      - 'control_python/**'
      - 'minimal_python/**'
      - 'monitor_python/**'
  
      
jobs:
  package_math_tools:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
  
    - name: Package App
      run: |
        cd MathTools
        chmod +x package.sh
        ./package.sh

    - name: Export Package
      uses: actions/upload-artifact@v7
      with:
        name: MathTools.zip
        path: MathTools/MathTools.zip
        archive: false

    
  package_position_logger:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
  
    - name: Package App
      run: |
        cd PositionLogger
        chmod +x package.sh
        ./package.sh

    - name: Export Package
      uses: actions/upload-artifact@v7
      with:
        name: PositionLogger.zip
        path: PositionLogger/PositionLogger.zip
        archive: false


  package_control_app:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
  
    - name: Package App
      run: |
        cd control_python
        chmod +x package.sh
        ./package.sh

    - name: Export Package
      uses: actions/upload-artifact@v7
      with:
        name: control_app_python.zip
        path: control_python/control_app_python.zip
        archive: false
  

  package_minimal_app:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
  
    - name: Package App
      run: |
        cd minimal_python
        chmod +x package.sh
        ./package.sh

    - name: Export Package
      uses: actions/upload-artifact@v7
      with:
        name: minimal_app_python.zip
        path: minimal_python/minimal_app_python.zip
        archive: false


  package_monitor_app:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v7
  
    - name: Package App
      run: |
        cd monitor_python
        chmod +x package.sh
        ./package.sh

    - name: Export Package
      uses: actions/upload-artifact@v7
      with:
        name: monitor_app_python.zip
        path: monitor_python/monitor_app_python.zip
        archive: false


  # Builds the SBOMs
  sbom:
    runs-on: ubuntu-latest
    needs: [package_math_tools, package_position_logger, package_control_app, package_minimal_app, package_monitor_app]
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v7
    
    - name: Get the SBOM enrichment tool
      uses: actions/checkout@v7
      with:
        repository: CommonplaceRobotics/SW_SBOM_Enrichment
        path: ${{ github.workspace }}/sbom_tool
        sparse-checkout: |
          SbomEnrichment.py
        sparse-checkout-cone-mode: false

    - name: Get the MinimalApp package
      uses: actions/download-artifact@v8
      with:
        name: minimal_app_python.zip
        path: minimal_python
        skip-decompress: true
        
    - name: Get the MonitorApp package
      uses: actions/download-artifact@v8
      with:
        name: monitor_app_python.zip
        path: monitor_python
        skip-decompress: true
        
    - name: Get the ControlApp package
      uses: actions/download-artifact@v8
      with:
        name: control_app_python.zip
        path: control_python
        skip-decompress: true
        
    - name: Get the MathTools App package
      uses: actions/download-artifact@v8
      with:
        name: MathTools.zip
        path: MathTools
        skip-decompress: true
        
    - name: Get the PositionLogger App package
      uses: actions/download-artifact@v8
      with:
        name: PositionLogger.zip
        path: PositionLogger
        skip-decompress: true

    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cyclonedx-bom

    # Liest die Core-Version aus CMakeLists.txt
    - name: Get software versions
      run: |
        MINIMAL_APP_VER=`grep -E -o "version[[:blank:]]*=[[:blank:]]*\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+" minimal_python/rcapp.xml | sed "s/[^0-9.]*//g"`
        MONITOR_APP_VER=`grep -E -o "version[[:blank:]]*=[[:blank:]]*\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+" monitor_python/rcapp.xml | sed "s/[^0-9.]*//g"`
        CONTROL_APP_VER=`grep -E -o "version[[:blank:]]*=[[:blank:]]*\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+" control_python/rcapp.xml | sed "s/[^0-9.]*//g"`
        MATH_TOOLS_APP_VER=`grep -E -o "version[[:blank:]]*=[[:blank:]]*\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+" MathTools/rcapp.xml | sed "s/[^0-9.]*//g"`
        POSITION_LOGGER_APP_VER=`grep -E -o "version[[:blank:]]*=[[:blank:]]*\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+" PositionLogger/rcapp.xml | sed "s/[^0-9.]*//g"`
        echo "Minimal App version '$MINIMAL_APP_VER' detected"
        echo "Monitor App version '$MONITOR_APP_VER' detected"
        echo "Control App version '$CONTROL_APP_VER' detected"
        echo "Math Tools App version '$MATH_TOOLS_APP_VER' detected"
        echo "Position Logger App version '$POSITION_LOGGER_APP_VER' detected"
        echo "MINIMAL_APP_VER=$MINIMAL_APP_VER" >> $GITHUB_ENV
        echo "MONITOR_APP_VER=$MONITOR_APP_VER" >> $GITHUB_ENV
        echo "CONTROL_APP_VER=$CONTROL_APP_VER" >> $GITHUB_ENV
        echo "MATH_TOOLS_APP_VER=$MATH_TOOLS_APP_VER" >> $GITHUB_ENV
        echo "POSITION_LOGGER_APP_VER=$POSITION_LOGGER_APP_VER" >> $GITHUB_ENV
        
    - name: Create output directory
      run: |
        mkdir ~/sboms

    - name: Create SBOM for MinimalApp
      uses: sbomify/sbomify-action@master
      env:
        WORKING_DIR: minimal_python
        LOCK_FILE: poetry.lock
        OUTPUT_FILE: ../sboms/sbom_minimal_app_python.cdx.json
        COMPONENT_NAME: Minimal App Python
        COMPONENT_VERSION: ${{ env.MINIMAL_APP_VER }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        UPLOAD: false

    - name: Create SBOM for MonitorApp
      uses: sbomify/sbomify-action@master
      env:
        WORKING_DIR: monitor_python
        LOCK_FILE: poetry.lock
        OUTPUT_FILE: ../sboms/sbom_monitor_app_python.cdx.json
        COMPONENT_NAME: Monitor App Python
        COMPONENT_VERSION: ${{ env.MONITOR_APP_VER }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        UPLOAD: false

    - name: Create SBOM for ControlApp
      uses: sbomify/sbomify-action@master
      env:
        WORKING_DIR: control_python
        LOCK_FILE: poetry.lock
        OUTPUT_FILE: ../sboms/sbom_control_app_python.cdx.json
        COMPONENT_NAME: Control App Python
        COMPONENT_VERSION: ${{ env.CONTROL_APP_VER }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        UPLOAD: false
        
    - name: Create SBOM for MathTools
      uses: sbomify/sbomify-action@master
      env:
        WORKING_DIR: MathTools
        LOCK_FILE: poetry.lock
        OUTPUT_FILE: ../sboms/sbom_math_tools_app.cdx.json
        COMPONENT_NAME: Math Tools App
        COMPONENT_VERSION: ${{ env.MATH_TOOLS_APP_VER }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        UPLOAD: false
        
    - name: Create SBOM for PositionLogger
      uses: sbomify/sbomify-action@master
      env:
        WORKING_DIR: PositionLogger
        LOCK_FILE: poetry.lock
        OUTPUT_FILE: ../sboms/sbom_position_logger_app.cdx.json
        COMPONENT_NAME: Position Logger App
        COMPONENT_VERSION: ${{ env.POSITION_LOGGER_APP_VER }}
        # Produkt- und Firmeninfo werden aus sbomify.json geladen
        AUGMENT: true
        # Metadaten aus Paket-Registry hinzufügen
        ENRICH: true
        UPLOAD: false
        
    - name: Final SBOM enrichment
      run: |
        sudo chmod 666 sboms/*
        python3 ${{ github.workspace }}/sbom_tool/SbomEnrichment.py .github/workflows/sbom_enrichment_db.json sboms/sbom_minimal_app_python.cdx.json
        python3 ${{ github.workspace }}/sbom_tool/SbomEnrichment.py .github/workflows/sbom_enrichment_db.json sboms/sbom_monitor_app_python.cdx.json
        python3 ${{ github.workspace }}/sbom_tool/SbomEnrichment.py .github/workflows/sbom_enrichment_db.json sboms/sbom_control_app_python.cdx.json
        python3 ${{ github.workspace }}/sbom_tool/SbomEnrichment.py .github/workflows/sbom_enrichment_db.json sboms/sbom_math_tools_app.cdx.json
        python3 ${{ github.workspace }}/sbom_tool/SbomEnrichment.py .github/workflows/sbom_enrichment_db.json sboms/sbom_position_logger_app.cdx.json

    - name: Export SBOMs
      uses: actions/upload-artifact@v7
      with:
        name: sboms
        path: sboms
        archive: true

    - uses: actions/setup-go@v6

    - name: Install SBOM QA tool
      run: go install github.com/interlynk-io/sbomqs@latest

    - name: SBOM quality score for MinimalApp
      run: sbomqs score sboms/sbom_minimal_app_python.cdx.json

    - name: SBOM quality score for MonitorApp
      run: sbomqs score sboms/sbom_monitor_app_python.cdx.json

    - name: SBOM quality score for ControlApp
      run: sbomqs score sboms/sbom_control_app_python.cdx.json
      
    - name: SBOM quality score for MathTools
      run: sbomqs score sboms/sbom_math_tools_app.cdx.json
      
    - name: SBOM quality score for PositionLogger
      run: sbomqs score sboms/sbom_position_logger_app.cdx.json

    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance for MinimalApp
      run: sbomqs compliance --bsi-v2 --color sboms/sbom_minimal_app_python.cdx.json

    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance for MonitorApp
      run: sbomqs compliance --bsi-v2 --color sboms/sbom_monitor_app_python.cdx.json

    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance for ControlApp
      run: sbomqs compliance --bsi-v2 --color sboms/sbom_control_app_python.cdx.json
      
    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance for MathTools
      run: sbomqs compliance --bsi-v2 --color sboms/sbom_math_tools_app.cdx.json
      
    # Checks compliance with the latest version of BSI TR-03183-2
    - name: Check CRA compliance for PositionLogger
      run: sbomqs compliance --bsi-v2 --color sboms/sbom_position_logger_app.cdx.json

    - name: List component licenses for MinimalApp
      run: sbomqs list --feature comp_with_declared_license --show sboms/sbom_minimal_app_python.cdx.json

    - name: List component licenses for MonitorApp
      run: sbomqs list --feature comp_with_declared_license --show sboms/sbom_monitor_app_python.cdx.json

    - name: List component licenses for Control App
      run: sbomqs list --feature comp_with_declared_license --show sboms/sbom_control_app_python.cdx.json
      
    - name: List component licenses for MathTools
      run: sbomqs list --feature comp_with_declared_license --show sboms/sbom_math_tools_app.cdx.json
      
    - name: List component licenses for PositionLogger
      run: sbomqs list --feature comp_with_declared_license --show sboms/sbom_position_logger_app.cdx.json

    # Security Audit
    - name: Scan for vulnerabilities for MinimalApp
      uses: anchore/scan-action@v7
      with:
        sbom: sboms/sbom_minimal_app_python.cdx.json

    - name: Scan for vulnerabilities for MonitorApp
      uses: anchore/scan-action@v7
      with:
        sbom: sboms/sbom_monitor_app_python.cdx.json

    - name: Scan for vulnerabilities for ControlApp
      uses: anchore/scan-action@v7
      with:
        sbom: sboms/sbom_control_app_python.cdx.json
        
    - name: Scan for vulnerabilities for MathTools
      uses: anchore/scan-action@v7
      with:
        sbom: sboms/sbom_math_tools_app.cdx.json
        
    - name: Scan for vulnerabilities for PositionLogger
      uses: anchore/scan-action@v7
      with:
        sbom: sboms/sbom_position_logger_app.cdx.json




# TODO:
# - Lockfiles generieren (poetry oder uv)
# - wheels bauen?