# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Python Apps

on:
  push:
    branches: [ "master", "v1*", "v2*", "v3*", "ci" ]
    paths:
      - ".github/**"
      - 'MathTools/**'
      - 'PositionLogger/**'
      - 'control_python/**'
      - 'minimal_python/**'
      - 'monitor_python/**'
  pull_request:
    branches: [ "master", "v1*", "v2*", "v3*" ]
    paths:
      - ".github/**"
      - 'MathTools/**'
      - 'PositionLogger/**'
      - 'control_python/**'
      - 'minimal_python/**'
      - 'monitor_python/**'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # Note: The poetry version must match the version that created the lock files.
    # The Python version used here limits the poetry version, so the
    # Lockfiles should be created with Python 3.9
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry flake8


    - name: MathTools - Install dependencies
      working-directory: ./MathTools
      run: poetry install

    - name: MathTools - Run tests
      working-directory: ./MathTools
      run: poetry run pytest


    - name: PositionLogger - Install dependencies
      working-directory: ./PositionLogger
      run: poetry install

    - name: PositionLogger - Run tests
      working-directory: ./PositionLogger
      run: poetry run pytest


    - name: MinimalApp - Install dependencies
      working-directory: ./minimal_python
      run: poetry install

    - name: MinimalApp - Run tests
      working-directory: ./minimal_python
      run: poetry run pytest


    - name: MonitorApp - Install dependencies
      working-directory: ./monitor_python
      run: poetry install

    - name: MonitorApp - Run tests
      working-directory: ./monitor_python
      run: poetry run pytest


    - name: ControlApp - Install dependencies
      working-directory: ./control_python
      run: poetry install

    - name: ControlApp - Run tests
      working-directory: ./control_python
      run: poetry run pytest


    - name: MathTools - Lint
      working-directory: ./MathTools
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: PositionLogger - Lint
      working-directory: ./MathTools
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: MinimalApp - Lint
      working-directory: ./MathTools
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: MonitorApp - Lint
      working-directory: ./MathTools
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: ControlApp - Lint
      working-directory: ./MathTools
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
